name: FridgeMVPiOS
options:
  minimumXcodeGenVersion: 2.38.0
configs:
  Debug: debug
  Release: release
targets:
  FridgeMVPiOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: FridgeMVPiOS
    info:
      path: FridgeMVPiOS/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yeongbin.fridgemvpios
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: 5.0
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
    scheme:
      gatherCoverageData: false
